{
 "title": "Dashboard Exemple - Azion - HOMOLOG",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0" },
   {
    "name": "host",
    "label": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Http Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Status by %",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "httpEvents",
     "endTimePath": "endTime",
     "groupBy": "[]",
     "queryText": "     query {\n  httpEvents(\n    limit: 10000,\n    filter: {\n      tsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n      host: \"$host\",\n      #statusRange: { begin: 300, end: 399 }\n    },\n    aggregate: {count: host} \n    groupBy: [status]\n  ) {\n    status\n    count\n  }\n}\n",
     "timePath": "tsRange"
    }
   ]
  },
  {
   "title": "Status 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "aliasBy": "2XX",
     "constant": 6.5,
     "dataPath": "httpEvents",
     "endTimePath": "endTime",
     "groupBy": "[]",
     "queryText": "     query {\n  httpEvents(\n    limit: 10000,\n    filter: {\n      tsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n      host: \"$host\",\n      statusRange: { begin: 200, end: 299 }\n    },\n    aggregate: {count: status} \n    groupBy: [ts, status]\n  ) {\n    ts\n    count\n  }\n}\n",
     "timePath": "tsRange"
    }
   ]
  },
  {
   "title": "Status 3xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
   "targets": [
    {
     "aliasBy": "2XX",
     "constant": 6.5,
     "dataPath": "httpEvents",
     "endTimePath": "endTime",
     "groupBy": "[]",
     "queryText": "     query {\n  httpEvents(\n    limit: 10000,\n    filter: {\n      tsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n      host: \"$host\",\n      statusRange: { begin: 300, end: 399 }\n    },\n    aggregate: {count: status} \n    groupBy: [ts, status]\n  ) {\n    ts\n    count\n  }\n}\n",
     "timePath": "tsRange"
    }
   ]
  },
  {
   "title": "TOp 10  hosts",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "httpEvents",
     "endTimePath": "endTime",
     "groupBy": "host",
     "queryText": "query {\n      httpEvents(\n   limit: 10,\n   filter: {\n\ttsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" }\n\t \n\t\t},\n   aggregate: {count: host}  \n   groupBy: [host,status]\n   #orderBy: [count_DESC]\n   )\n {\n   host\n  #status\n   count\n   \n }\n}",
     "timePath": "tsRange"
    }
   ]
  },
  {
   "title": "Status 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
   "targets": [
    {
     "aliasBy": "4XX",
     "constant": 6.5,
     "dataPath": "httpEvents",
     "endTimePath": "endTime",
     "groupBy": "[]",
     "queryText": "     query {\n  httpEvents(\n    limit: 10000,\n    filter: {\n      tsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n      host: \"$host\",\n      statusRange: { begin: 400, end: 499 }\n    },\n    aggregate: {count: status} \n    groupBy: [ts, status]\n  ) {\n    ts\n    count\n  }\n}\n",
     "timePath": "tsRange"
    }
   ]
  },
  {
   "title": "Status 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 9 },
   "targets": [
    {
     "aliasBy": "2XX",
     "constant": 6.5,
     "dataPath": "httpEvents",
     "endTimePath": "endTime",
     "groupBy": "[]",
     "queryText": "     query {\n  httpEvents(\n    limit: 10000,\n    filter: {\n      tsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n      host: \"$host\",\n      statusRange: { begin: 500, end: 599 }\n    },\n    aggregate: {count: status} \n    groupBy: [ts, status]\n  ) {\n    ts\n    count\n  }\n}\n",
     "timePath": "tsRange"
    }
   ]
  },
  {
   "title": "TOp 10  User Agents",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "httpEvents",
     "endTimePath": "endTime",
     "groupBy": "httpUserAgent",
     "queryText": "query {\n      httpEvents(\n   limit: 10,\n    filter: {\n\ttsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n\thost: \"$host\"\n\t \n\t\t},\n   aggregate: {count: host}  \n   groupBy: [httpUserAgent]\n   orderBy: [count_DESC]\n   )\n {\n   httpUserAgent\n   #status\n   count\n   \n }\n}",
     "timePath": "tsRange"
    }
   ]
  },
  {
   "title": "Top 10  requestUri",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "httpEvents",
     "endTimePath": "endTime",
     "groupBy": "time",
     "queryText": "query {\n      httpEvents(\n   limit: 100,\n   filter: {\n\ttsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n\thost: \"$host\"\n\t \n\t\t},\n   aggregate: {count: requestUri}  \n   groupBy: [ts, requestUri]\n   orderBy: [count_DESC]\n   )\n {\n   ts\n   requestUri\n  #status\n   count\n   \n }\n}",
     "timePath": "tsRange"
    }
   ]
  },
  {
   "title": "HTTP Status by %",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "httpEvents",
     "endTimePath": "endTime",
     "groupBy": "[]",
     "queryText": "     query {\n  httpEvents(\n    limit: 10000,\n    filter: {\n      tsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n      host: \"$host\",\n    },\n    aggregate: {count: host} \n    groupBy: [httpUserAgent]\n    orderBy: [count_DESC]\n  ) {\n    httpUserAgent\n    count\n  }\n}\n",
     "timePath": "tsRange"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "HTTP info",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "httpEvents",
     "endTimePath": "endTime",
     "groupBy": "time",
     "queryText": "query {\n  httpEvents(\n    limit: 10,\n    filter: {\n      tsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n      host: \"$host\"\n    },\n    groupBy: [host, status, ts, source, requestTime, upstreamCacheStatus, proxyStatus, upstreamStatus, upstreamBytesReceived, requestUri, upstreamConnectTime, upstreamResponseTime, remoteAddress, httpUserAgent, upstreamAddr, serverAddr]\n  ) {\n    ts\n    source\n    host\n    requestTime\n    upstreamCacheStatus\n    status\n    proxyStatus\n    upstreamStatus\n    upstreamBytesReceived\n    requestUri\n    upstreamConnectTime\n    upstreamResponseTime\n    remoteAddress\n    httpUserAgent\n    upstreamAddr\n    serverAddr\n  }\n}\n",
     "timePath": "tsRange"
    }
   ]
  }
 ]
}